Repository PrincetonUniversity/STELLOPT, pull requests merged in 2024-10, with the labels that each got.

#287 Bugfix/dkes sopt interface
  DKES/DKES.dep
  DKES/ObjectList
  DKES/Sources/Input_Prep/dkes_input_prepare_old.f
  STELLOPTV2/Sources/General/stellopt_dkes.f90
Labels: bug

#288 STELLOPT: Allow _opt files for automated zipping in some scenarios.
  STELLOPTV2/Sources/General/stellopt_optimize.f90
Labels: enhancement

#292 Merge of feature/thrift from file to THRIFT
  THRIFT/Sources/thrift_funcs.f90
  THRIFT/Sources/thrift_init.f90
  THRIFT/Sources/thrift_input_mod.f90
  THRIFT/Sources/thrift_profiles_mod.f90
  THRIFT/Sources/thrift_run_bootstrap.f90
  THRIFT/Sources/thrift_runtime.f90
  pySTEL/libstell/dkes.py
  pySTEL/libstell/penta.py
  pySTEL/libstell/plasma.py
  pySTEL/libstell/thrift.py
Labels: enhancement

#293 Merge of feature/thrift_restart into develop and feature/THRIFT_DKES_PENTA
  THRIFT/Sources/thrift_init.f90
  THRIFT/Sources/thrift_input_mod.f90
  THRIFT/Sources/thrift_interface_mod.f90
  THRIFT/Sources/thrift_jinductive.f90
  THRIFT/Sources/thrift_runtime.f90
  THRIFT/Sources/thrift_vars.f90
  pySTEL/libstell/thrift.py
Labels: enhancement

#295 STELLOPT: Fixed bug related to renomalization and zip file generation.
  STELLOPTV2/Sources/General/stellopt_optimize.f90
Labels: bug

#297 FIELDLINES: Added verbose output and STOP field fieldlines has error.
  FIELDLINES/Sources/fieldlines_follow.f90
Labels: bug, enhancement
