Repository PrincetonUniversity/STELLOPT, pull requests merged in 2024-12, with the labels that each got.

#307 BEAMS3D: Ability to mark self-generated markers with population index
  BEAMS3D/Sources/beams3d_init.f90
  LIBSTELL/Sources/Modules/beams3d_input_mod.f90
  pySTEL/pyproject.toml
Labels: enhancement

#310 STELLOPT: Fixed two bugs in gamma_c calculation
  STELLOPTV2/Sources/Chisq/chisq_gamma_c.f90
  pySTEL/STELLOPT.py
Labels: bug

#318 Feature/py stel
  LIBSTELL/Sources/Modules/beams3d_input_mod.f90
  SHARE/make_macports.inc
  pySTEL/STELLOPT.py
  pySTEL/VMECplot.py
  pySTEL/coils_util.py
  pySTEL/focus_util.py
  pySTEL/libstell/beams3d.py
  pySTEL/libstell/boozer.py
  pySTEL/libstell/coils.py
  pySTEL/libstell/fieldlines.py
  pySTEL/libstell/libstell.py
  pySTEL/libstell/stellopt.py
  pySTEL/libstell/vmec.py
  pySTEL/libstell/wall.py
  pySTEL/pyproject.toml
  pySTEL/vmec2beams3d.py
  pySTEL/vmec2focus.py
  pySTEL/vmec_spectrum.py
  pySTEL/wall_util.py
Labels: bug, enhancement

#312 Feature/thrift vmec restart
  BENCHMARKS/VMEC_TEST/BENCH_DATA.json
  BENCHMARKS/VMEC_TEST/input.DIII-D_reset
  BENCHMARKS/VMEC_TEST/wout_reset.nc
  BENCHMARKS/makefile
  LIBSTELL/Sources/Miscel/profile_functions.f
  LIBSTELL/Sources/Modules/read_wout_mod.f90
  THRIFT/Sources/thrift_evolve.f90
  THRIFT/Sources/thrift_init.f90
  THRIFT/Sources/thrift_interface_mod.f90
  THRIFT/Sources/thrift_paraexe.f90
  THRIFT/Sources/thrift_reinit_vmec.f90
  THRIFT/Sources/thrift_run_equil.f90
  THRIFT/Sources/thrift_runtime.f90
  VMEC2000/Sources/General/add_fluxes.f90
  VMEC2000/Sources/General/bcovar.f
  VMEC2000/Sources/General/blocktridiagonalsolver.f90
  VMEC2000/Sources/General/blocktridiagonalsolver_bst.f90
  VMEC2000/Sources/General/forces.f
  VMEC2000/Sources/General/funct3d.f
  VMEC2000/Sources/General/jacobian.f
  VMEC2000/Sources/General/totzsp_mod.f
  VMEC2000/Sources/Initialization_Cleanup/allocate_nunv.f
  VMEC2000/Sources/Initialization_Cleanup/fixaray.f
  VMEC2000/Sources/Initialization_Cleanup/free_mem_nunv.f
  VMEC2000/Sources/Initialization_Cleanup/initialize_radial.f
  VMEC2000/Sources/Initialization_Cleanup/load_xc_from_wout.f
  VMEC2000/Sources/Initialization_Cleanup/profil1d.f
  VMEC2000/Sources/Input_Output/eqfor.f
  VMEC2000/Sources/Input_Output/jxbforce.f
  VMEC2000/Sources/Input_Output/readin.f
  VMEC2000/Sources/Input_Output/wrout.f
  VMEC2000/Sources/NESTOR_vacuum/scalpot.f
  VMEC2000/Sources/NESTOR_vacuum/vacmod.f
  VMEC2000/Sources/NESTOR_vacuum/vacuum.f
  VMEC2000/Sources/TimeStep/eqsolve.f
  VMEC2000/Sources/TimeStep/parallel_vmec_module.f90
  VMEC2000/Sources/TimeStep/runvmec.f
Labels: bug, enhancement

#317 Feature/beams3 d toroidal rotation
  BEAMS3D/Sources/beams3d_free.f90
  BEAMS3D/Sources/beams3d_grid.f90
  BEAMS3D/Sources/beams3d_init.f90
  BEAMS3D/Sources/beams3d_init_continuegrid.f90
  BEAMS3D/Sources/beams3d_init_eqdsk.f90
  BEAMS3D/Sources/beams3d_init_fieldlines.f90
  BEAMS3D/Sources/beams3d_init_vmec.f90
  BEAMS3D/Sources/beams3d_physics_mod.f90
  BEAMS3D/Sources/beams3d_runtime.f90
  BEAMS3D/Sources/beams3d_write.f90
  BEAMS3D/Sources/beams3d_write_ascoth4.f90
  BEAMS3D/Sources/fidasim_input_mod.f90
  BENCHMARKS/BEAMS3D_TEST/compare.py
  LIBSTELL/Sources/Modules/beams3d_globals.f90
  LIBSTELL/Sources/Modules/beams3d_input_mod.f90
  pySTEL/libstell/beams3d.py
Labels: enhancement

#321 STELLOPT: 2D Rosenbrock test feature
  LIBSTELL/Sources/Optimization/DE2_Evolve.f
  LIBSTELL/Sources/STELLOPT/stellopt_input_mod.f90
  LIBSTELL/Sources/STELLOPT/stellopt_targets.f90
  STELLOPTV2/ObjectList
  STELLOPTV2/STELLOPTV2.dep
  STELLOPTV2/Sources/Chisq/chisq_rosenbrock2d.f90
  STELLOPTV2/Sources/General/stellopt_fcn.f90
  STELLOPTV2/Sources/General/stellopt_load_targets.f90
  STELLOPTV2/Sources/General/stellopt_renorm.f90
Labels: bug, enhancement

#327 LIBSTELL: Bugfix for the particle swarm optimization.
  LIBSTELL/Sources/Optimization/PSO_Evolve.f
Labels: bug

#328 Feature/py stel
  LIBSTELL/Sources/Modules/vmec_utils.f
  pySTEL/STELLOPT.py
  pySTEL/STELLOPT.ui
  pySTEL/VMECplot.py
  pySTEL/libstell/boozer.py
  pySTEL/libstell/coils.py
  pySTEL/libstell/gist.py
  pySTEL/libstell/libstell.py
  pySTEL/libstell/nescoil.py
  pySTEL/libstell/stellopt.py
  pySTEL/libstell/vmec.py
  pySTEL/libstell/wall.py
Labels: enhancement
