Repository PrincetonUniversity/STELLOPT, pull requests merged in 2024-11, with the labels that each got.

#298 VMEC2000: Now catch and handle TimeStepControl error.
  VMEC2000/Sources/General/vmec_params.f
  VMEC2000/Sources/Input_Output/fileout.f
  VMEC2000/Sources/TimeStep/evolve.f
Labels: bug, enhancement

#300 Spell "beams3d" correctly on its docs page
  BEAMS3D.md
Labels: documentation

#299 VMEC2STEL Update
  VMEC2STEL/Sources/vmec2stel_main.f90
Labels: bug, enhancement

#289 Feature/py stel
  .gitignore
  LIBSTELL/Sources/Modules/beams3d_input_mod.f90
  LIBSTELL/Sources/Modules/vmec_input.f
  LIBSTELL/Sources/STELLOPT/stellopt_globals.f90
  LIBSTELL/Sources/STELLOPT/stellopt_input_mod.f90
  LIBSTELL/Sources/STELLOPT/stellopt_vars.f90
  build_all
  makefile
  pySTEL/FIELDLINESplot.py
  pySTEL/STELLOPT.py
  pySTEL/STELLOPT.ui
  pySTEL/VMECplot.py
  pySTEL/beams3d_util.py
  pySTEL/coils_util.py
  pySTEL/fieldlines_util.py
  pySTEL/focus_util.py
  pySTEL/gist_util.py
  pySTEL/libstell/beams3d.py
  pySTEL/libstell/coils.py
  pySTEL/libstell/fieldlines.py
  pySTEL/libstell/fusion.py
  pySTEL/libstell/gist.py
  pySTEL/libstell/libstell.py
  pySTEL/libstell/plot3D.py
  pySTEL/libstell/stellopt.py
  pySTEL/libstell/vmec.py
  pySTEL/libstell/wall.py
  pySTEL/make_mesh.py
  pySTEL/setup.py
  pySTEL/vmec2beams3d.py
  pySTEL/vmec_util.py
Labels: enhancement

#306 Feature/osx python improvements
  LIBSTELL/Sources/Modules/fieldlines_input_mod.f90
  SHARE/make_macports.inc
  build_all
  makefile
  pySTEL/pyproject.toml
  pySTEL/setup.py
Labels: bug, enhancement

#308 Bugfix/stellopt dkes alpha
  STELLOPTV2/Sources/Chisq/chisq_dkes.f90
  STELLOPTV2/Sources/Chisq/chisq_dkes_alpha.f90
  STELLOPTV2/Sources/Chisq/chisq_dkes_erdiff.f90
  pySTEL/STELLOPT.py
Labels: bug

#311 Merge of feature/THRIFT_improve into develop
  DKES/Sources/General/printout.f
  PENTA/Sources/penta_interface_mod.f90
  THRIFT/Sources/thrift_boozer.f90
  THRIFT/Sources/thrift_dkes.f90
  THRIFT/Sources/thrift_evolve.f90
  THRIFT/Sources/thrift_init.f90
  THRIFT/Sources/thrift_interface_mod.f90
  THRIFT/Sources/thrift_penta.f90
  THRIFT/Sources/thrift_vars.f90
  THRIFT/Sources/thrift_write.f90
  pySTEL/libstell/penta.py
  pySTEL/libstell/plasma.py
  pySTEL/libstell/thrift.py
Labels: bug, enhancement
