Repository PrincetonUniversity/STELLOPT, pull requests merged in 2025-01, with the labels that each got.

#333 BEAMS3D: Bugfix for uninitialized variable in beams3d_physics_mod.
  BEAMS3D/Sources/beams3d_physics_mod.f90
Labels: bug

#334 BEAMS3D: removed bsign from fidasim interface
  BEAMS3D/Sources/fidasim_input_mod.f90
Labels: bug

#335 Bugfix/b3 d thermalization
  BEAMS3D/Sources/beams3d_physics_mod.f90
Labels: bug

#336 Merge feature/thrift_files into develop
  PENTA/Sources/penta_interface_mod.f90
  THRIFT/Sources/thrift_equil_p.f90
  THRIFT/Sources/thrift_evolve.f90
  THRIFT/Sources/thrift_funcs.f90
  THRIFT/Sources/thrift_init.f90
  THRIFT/Sources/thrift_interface_mod.f90
  THRIFT/Sources/thrift_penta.f90
  THRIFT/Sources/thrift_vars.f90
  THRIFT/Sources/thrift_write.f90
  pySTEL/libstell/collisions.py
  pySTEL/libstell/fusion.py
  pySTEL/libstell/plasma.py
  pySTEL/libstell/popcon.py
  pySTEL/libstell/thrift.py
Labels: enhancement

#337 Feature/vmec rescale
  LIBSTELL/LIBSTELL.dep
  LIBSTELL/Sources/Modules/vmec_input.f
  VMEC2000/Sources/Input_Output/readin.f
Labels: enhancement

#338 Bugfix/stellopt tvolume
  LIBSTELL/Sources/Modules/beams3d_input_mod.f90
  LIBSTELL/Sources/Modules/read_nescoil_mod.f90
  STELLOPTV2/Sources/General/stellopt_fcn.f90
  STELLOPTV2/Sources/General/stellopt_reinit_vmec.f90
  pySTEL/STELLOPT.py
  pySTEL/VMECplot.py
  pySTEL/beams3d_util.py
  pySTEL/libstell/beams3d.py
  pySTEL/libstell/coils.py
  pySTEL/libstell/fieldlines.py
  pySTEL/libstell/gist.py
  pySTEL/libstell/libstell.py
  pySTEL/libstell/nescoil.py
  pySTEL/libstell/vmec.py
  pySTEL/libstell/wall.py
  pySTEL/nescoil_util.py
  pySTEL/vmec_util.py
Labels: bug, enhancement

#326 Feature/collision refactor
  BEAMS3D/BEAMS3D.dep
  BEAMS3D/Sources/beams3d_follow.f90
  BEAMS3D/Sources/beams3d_follow_fo.f90
  BEAMS3D/Sources/beams3d_follow_gc.f90
  BEAMS3D/Sources/beams3d_physics_mod.f90
  LIBSTELL/LIBSTELL.dep
  LIBSTELL/ObjectList
  LIBSTELL/Sources/Modules/collision_operators.f90
Labels: enhancement

#342 LIBSTELL: Improvements to the VMEC wout descriptions.
  LIBSTELL/Sources/Modules/read_wout_mod.f90
Labels: documentation
